micronaut:
  application:
    name: webIndexSearcher
netty:
  default:
    allocator:
      max-order: 3
elasticsearch:
  httpHosts: http://localhost:9200,http://127.0.0.2:9200
  indexes:
    movies: movies
